#测试环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmanage?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  security:
    user:
      name: user
      password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 30s
    key:
      authCode: 'ums:authCode'
      orderId: 'oms:orderId'
      member: 'ums:member'
    expire:
      authCode: 90 # 验证码超期时间
      common: 86400 # 24小时

jwt:
  tokenHeader: Authorization
  secret: wpa4sf6sf1as4d56w464aswq54asd45
  expiration: 604800
  tokenHead: 'Bearer '
