#测试环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmanage?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  security:
    user:
      name: user
      password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 300ms

jwt:
  tokenHeader: Authorization
  secret: d5a4sf6sf1as4d56w464e65q54asd45
  expiration: 604800
  tokenHead: 'Bearer '
